{"name": "test_fail1", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail1():\n>       assert False\nE       assert False\n\ntests/simple/test_fail.py:2: AssertionError"}, "start": 1741458130822, "stop": 1741458130822, "uuid": "b0458fdc-d34b-436b-8d74-e15b4d2a410f", "historyId": "dc0ceebed11c4ccce398ae2314fa1cd9", "testCaseId": "5980a0f138d2262d80936b48f834090e", "fullName": "tests.simple.test_fail#test_fail1", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MBP16M1MAX.local"}, {"name": "thread", "value": "49676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}