{"name": "test_fail5", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail5():\n>       assert False\nE       assert False\n\ntests/simple/test_fail.py:14: AssertionError"}, "start": 1741458130839, "stop": 1741458130839, "uuid": "035bc155-056c-45ac-9113-2caeba76a25b", "historyId": "0fef2d7cf3da80e165e4bf69df443b68", "testCaseId": "3ed4406b36bfdd2ca409ebda6d8af2cc", "fullName": "tests.simple.test_fail#test_fail5", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MBP16M1MAX.local"}, {"name": "thread", "value": "49676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}