{"name": "test_fail3", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail3():\n>       assert False\nE       assert False\n\ntests/simple/test_fail.py:8: AssertionError"}, "start": 1741458130837, "stop": 1741458130837, "uuid": "e3cab02f-4a53-49bf-899c-beca9649b00d", "historyId": "939d0d34fdd0a77844bacb76dac07bab", "testCaseId": "3871665697ea3d8351c8bbb21a2393bd", "fullName": "tests.simple.test_fail#test_fail3", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MBP16M1MAX.local"}, {"name": "thread", "value": "49676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}