{"name": "test_fail4", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail4():\n>       assert False\nE       assert False\n\ntests/simple/test_fail.py:11: AssertionError"}, "start": 1741458130838, "stop": 1741458130838, "uuid": "10b594f5-d42e-4963-8eaa-cbc21dc70e05", "historyId": "3f477f2a768892a9257adc9bf32579eb", "testCaseId": "f9f49e04500ac018e8389a41fc795dc7", "fullName": "tests.simple.test_fail#test_fail4", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MBP16M1MAX.local"}, {"name": "thread", "value": "49676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}